name: my-first-workflow
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome message
        run: echo "Welcome mohamed, from github actions"
